export const baseBalls = [
    { name: 'Dash',    color: '#06b6d4', ability: 'Dash',      hp: 104, maxHp: 104, r: 56, mass: 1.0, speed: 4.9, damage: 9,  desc: 'High speed, dashes forward to strike.' },
    { name: 'Titan',   color: '#94a3b8', ability: 'Heavy',     hp: 170, maxHp: 170, r: 80, mass: 2.2, speed: 2.2, damage: 10, desc: 'Massive, high HP, turns slowly.' },
    { name: 'Dracula', color: '#ef4444', ability: 'Vampire',   hp: 114, maxHp: 114, r: 61, mass: 1.2, speed: 3.5, damage: 11, desc: 'Heals 50% of damage dealt by its weapon.' },
    { name: 'Ninja',   color: '#71717a', ability: 'Teleport',  hp: 94,  maxHp: 94,  r: 57, mass: 0.9, speed: 4.5, damage: 12, desc: 'Periodically teleports behind the opponent.' },
    { name: 'Zerk',    color: '#f97316', ability: 'Berserk',   hp: 122, maxHp: 122, r: 66, mass: 1.4, speed: 3.3, damage: 9,  desc: 'Damage and speed massively increase as HP drops.' },
    { name: 'Paladin', color: '#3b82f6', ability: 'Shield',    hp: 124, maxHp: 124, r: 66, mass: 1.4, speed: 2.9, damage: 10, desc: 'Periodically regenerates a protective shield.' },
    { name: 'Venom',   color: '#22c55e', ability: 'Poison',    hp: 116, maxHp: 116, r: 60, mass: 1.1, speed: 3.9, damage: 10, desc: 'Frontal strikes apply dangerous Damage-Over-Time.' },
    { name: 'Mage',    color: '#a855f7', ability: 'Missile',   hp: 112, maxHp: 112, r: 55, mass: 0.8, speed: 4.1, damage: 10, desc: 'Stays away and fires homing magic missiles.' },
    { name: 'Spike',   color: '#d97706', ability: 'Trap',      hp: 112, maxHp: 112, r: 58, mass: 1.1, speed: 3.9, damage: 9,  desc: 'Leaves volatile traps behind.' },
    { name: 'Sniper',  color: '#fcd34d', ability: 'Laser',     hp: 98,  maxHp: 98,  r: 53, mass: 0.8, speed: 4.2, damage: 10, desc: 'Fires fast, non-homing piercing shots.' },
    { name: 'Hook',    color: '#8b5cf6', ability: 'Grapple',   hp: 124, maxHp: 124, r: 61, mass: 1.3, speed: 3.7, damage: 9,  desc: 'Violently pulls the enemy towards itself.' },
    { name: 'Ghost',   color: '#cbd5e1', ability: 'Phase',     hp: 96,  maxHp: 96,  r: 56, mass: 0.9, speed: 4.9, damage: 11, desc: 'Periodically becomes intangible to attacks.' },
    { name: 'Pulsar',  color: '#0ea5e9', ability: 'Pulse',     hp: 128, maxHp: 128, r: 68, mass: 1.5, speed: 2.9, damage: 8,  desc: 'Emits a repelling, damaging energy shockwave.' },
    { name: 'Swarm',   color: '#a3e635', ability: 'Minion',    hp: 116, maxHp: 116, r: 59, mass: 1.0, speed: 4.0, damage: 8,  desc: 'Spawns small homing drones to harass.' },
    { name: 'Thorn',   color: '#14b8a6', ability: 'Reflect',   hp: 150, maxHp: 150, r: 66, mass: 1.7, speed: 2.9, damage: 8,  desc: 'Reflects 40% of taken damage back to attacker.' },
    { name: 'Comet',   color: '#fb923c', ability: 'Charge',    hp: 116, maxHp: 116, r: 61, mass: 1.4, speed: 3.1, damage: 12, desc: 'Builds massive momentum in a straight line.' },
    { name: 'Razor',   color: '#f59e0b', ability: 'Boomerang', hp: 114, maxHp: 114, r: 60, mass: 1.1, speed: 3.8, damage: 9,  desc: 'Throws a curved blade that can hit on the way out and back.' },
    { name: 'Malik',   color: '#111827', ability: 'Brand',     hp: 110, maxHp: 110, r: 60, mass: 1.0, speed: 3.6, damage: 9,  desc: 'Black flame hits permanently reduce the enemy max HP.' },
    { name: 'Enma',    color: '#dc2626', ability: 'Scythe',    hp: 112, maxHp: 112, r: 61, mass: 1.1, speed: 3.9, damage: 10, desc: 'Wide melee hits steal max HP and grow stronger over time.' },
    { name: 'Vanta',   color: '#312e81', ability: 'Last Stand',hp: 124, maxHp: 124, r: 64, mass: 1.4, speed: 3.1, damage: 9,  desc: 'Gains damage and damage reduction as HP gets lower.' }
];
